version: '3.7'

volumes:
  db:
    driver: local

services:
  shebanqapp:
    image: registry.diginfra.net/vicd/shebanqapp:${dockertag}
    # restart: unless-stopped
    container_name: shebanqapp
    hostname: shebanqapp
    environment:
      gitlocation: ${gitlocation}
      hostname: ${hostname}
      mysqlrootpwd: ${mysqlrootpwd}
      mysqluser: ${mysqluser}
      mysqluserpwd: ${mysqluserpwd}
    entrypoint: ["./start.sh"]
    depends_on:
      - db
    volumes:
      - "./:/app"
    ports:
      - "${shebanqport}:${shebanqport}"

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=${mysqlrootpwd}
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
