version: '3.7'

volumes:
  data:
    driver: local

services:
  shebanq:
    # image: registry.diginfra.net/dirkr/shebanq:${dockertag}
    build: .
    # restart: unless-stopped
    container_name: shebanq
    hostname: shebanq
    environment:
      runmode: ${runmode}
      gitlocation: ${gitlocation}
      hostname: ${hostname}
      hostport: ${hostport}
      web2pyadminpwd: ${web2pyadminpwd}
      mysqlhost: ${mysqlhost}
      mysqlrootpwd: ${mysqlrootpwd}
      mysqluser: ${mysqluser}
      mysqluserpwd: ${mysqluserpwd}
    entrypoint: 
      - /bin/bash
      - /app/start.sh
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - "${hostport}:${hostport}"

  db:
    image: mariadb:10
    container_name: shebanqdb
    hostname: shebanqdb
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=${mysqlrootpwd}
      - MYSQL_USER=${mysqluser}
      - MYSQL_PASSWORD=${mysqluserpwd}
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
      - ./src/mysql:/etc/mysql/conf.d
