version: '3.7'

volumes:
  db:
    driver: local

services:
  shebanq:
    # image: registry.diginfra.net/dirkr/shebanq:${dockertag}
    build: .
    # restart: unless-stopped
    container_name: shebanq
    hostname: shebanq
    environment:
      maintenance: ${maintenance}
      gitlocation: ${gitlocation}
      hostname: ${hostname}
      mysqlrootpwd: ${mysqlrootpwd}
      mysqluser: ${mysqluser}
      mysqluserpwd: ${mysqluserpwd}
    entrypoint: ["./start.sh"]
    depends_on:
      - db
    volumes:
      - "./:/app"
    ports:
      - "${shebanqport}:${shebanqport}"

  db:
    image: mariadb:10
    container_name: shebanqdb
    hostname: shebanqdb
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=${mysqlrootpwd}
      - MYSQL_USER=${mysqluser}
      - MYSQL_PASSWORD=${mysqluserpwd}
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
